### ISSUE TITLE
runtime error.  AttributeError: 'Tensor' object has no attribute 'putLayer'

### ISSUE THREAD

**Issue by bezoldbrucke** [jakc4103/DFQ#1]
Hi, 

Thanks for the code. But with nothing changed, the code cannot run w/ the complaint: AttributeError: 'Tensor' object has no attribute 'putLayer'

1. do u have a requirment.txt so that we can follow your env?
2. The PyTransformer seems to be updating. Can you provide a folder (instead of a link) that works?

thanks a lot,
jun

here're the error output FYI.
Traceback (most recent call last):
  File "/newDisk/users/junjiang/project_from_server/DFQ/main.py", line 177, in <module>
    orig_main()
  File "/newDisk/users/junjiang/project_from_server/DFQ/main.py", line 91, in orig_main
    model = switch_layers(model, transformer, data)
  File "/newDisk/users/junjiang/project_from_server/DFQ/utils/layer_transform.py", line 194, in switch_layers
    transformer._build_graph(model, data) # construt graph after all state_dict loaded
  File "/newDisk/users/junjiang/project_from_server/DFQ/PyTransformer/transformers/torchTransformer.py", line 349, in _build_graph
    self.log = tmp_model.forward(self.log)		
  File "/newDisk/users/junjiang/project_from_server/DFQ/modeling/deeplab.py", line 29, in forward
    x, low_level_feat = self.backbone(input)
  File "/home/junjiang/anaconda3/envs/DFQ/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/newDisk/users/junjiang/project_from_server/DFQ/modeling/backbone/mobilenet.py", line 119, in forward
    low_level_feat = self.low_level_features(x)
  File "/home/junjiang/anaconda3/envs/DFQ/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/junjiang/anaconda3/envs/DFQ/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/junjiang/anaconda3/envs/DFQ/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/junjiang/anaconda3/envs/DFQ/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/junjiang/anaconda3/envs/DFQ/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/newDisk/users/junjiang/project_from_server/DFQ/PyTransformer/transformers/utils.py", line 354, in forward
    out_tensor = self.origin_layer(log_tensor).clone()
  File "/home/junjiang/anaconda3/envs/DFQ/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/newDisk/users/junjiang/project_from_server/DFQ/PyTransformer/transformers/utils.py", line 349, in forward
    cur_log.putLayer(self.origin_layer)
AttributeError: 'Tensor' object has no attribute 'putLayer'

**Comment by jakc4103** [comment]
Hi 

I've upload the requirement.txt, though its not related to the run time error.
I guess the error comes from the version of PyTransformer is not right; you should use the version it links to, or you could just use the latest version from 'hotfix' branch of PyTransformer.

Let me know if it work for you
tks
