### ISSUE TITLE
TypeError: new() received an invalid combination of arguments - got (NoneType, NoneType)

### ISSUE THREAD

**Issue by JohnnMason** [jakc4103/DFQ#28]
I have come across an unexpected problem when I run with "python3 main_cls.py --quantize --relu --equalize",

load weight: modeling/classification/mobilenetv2_1.0-f2a8633.pth.tar
register <class 'torch.nn.modules.activation.ReLU6'> <class 'torch.nn.modules.activation.ReLU'>
register <class 'torch.nn.modules.conv.Conv2d'> <class 'utils.quantize.QuantNConv2d'>
register <class 'torch.nn.modules.linear.Linear'> <class 'utils.quantize.QuantNLinear'>
Traceback (most recent call last):
  File "main_cls.py", line 214, in <module>
    main()
  File "main_cls.py", line 132, in main
    model, transformer = switch_layers(model, transformer, data, module_dict, ignore_layer=[QuantMeasure], quant_op=args.quantize)
  File "/home/notebook/code/personal/80296970/DFQ/utils/layer_transform.py", line 157, in switch_layers
    model = transformer.trans_layers(model, update=True if key == 1 else False)
  File "/home/notebook/code/personal/80296970/DFQ/PyTransformer/transformers/torchTransformer.py", line 84, in trans_layers
    _layer_new = self._register_dict[type(getattr(model, module_name))](**_kwargs) # only give positional args
  File "/home/notebook/code/personal/80296970/DFQ/utils/quantize.py", line 347, in __init__
    super(QuantNLinear, self).__init__(in_features, out_features, bias)
  File "/home/notebook/code/personal/80296970/dnn-quant-ocs/env/lib/python3.5/site-packages/torch/nn/modules/linear.py", line 72, in __init__
    self.weight = Parameter(torch.Tensor(out_features, in_features))
TypeError: new() received an invalid combination of arguments - got (NoneType, NoneType), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the arguments have invalid types: (NoneType, NoneType)
 * (object data, torch.device device)
      didn't match because some of the arguments have invalid types: (NoneType, NoneType)

Have you ever meet this problem and what is the solution? Thank you.

**Comment by JohnnMason** [comment]
This issue has been solved by using the "hotfix" branch of PyTransformer.
